vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO libgit2/libgit2
    REF "v${VERSION}"
    SHA512 85036ade3aca33c5283605ae9de21a7948ec5952bc8cd468aa024ca873851a56ab0ebe62f95c0da109df9163875e9687a377d3df69728d434cc258b3f845ef0c
    HEAD_REF main
    PATCHES
        # --- inherited from the stock vcpkg port ---
        c-standard.diff # for 'inline' in system headers
        cli-include-dirs.diff
        dependencies.diff
        mingw-winhttp.diff
        no-static-whole-program-optimization.diff # don't /GL a static lib; it forces /LTCG on consumers
        # --- TortoiseGit-specific, see TORTOISEGIT-PATCHES.md ---
        tortoisegit-safe-directory.diff
        tortoisegit-admin-owner-check.diff
        tortoisegit-enum-casts.diff
        tortoisegit-no-experimental-rename.diff
        tortoisegit-reverse-workdir-oid.diff
)

file(REMOVE_RECURSE
    "${SOURCE_PATH}/cmake/FindPCRE.cmake"
    "${SOURCE_PATH}/cmake/FindPCRE2.cmake"
    "${SOURCE_PATH}/deps/chromium-zlib"
    "${SOURCE_PATH}/deps/http-parser"
    "${SOURCE_PATH}/deps/pcre"
    "${SOURCE_PATH}/deps/winhttp"
    "${SOURCE_PATH}/deps/zlib"
)

string(COMPARE EQUAL "${VCPKG_CRT_LINKAGE}" "static" STATIC_CRT)

vcpkg_find_acquire_program(PKGCONFIG)

vcpkg_check_features(
    OUT_FEATURE_OPTIONS GIT2_FEATURES
    FEATURES
        tools   BUILD_CLI
        sha256  EXPERIMENTAL_SHA256
)

# Backend selection is pinned rather than derived from features: these values
# mirror ext/build/libgit2.vcxproj's PreprocessorDefinitions, which is the
# source of truth for how TortoiseGit has always built libgit2.
#   USE_HTTPS=WinHTTP        -> GIT_HTTPS, GIT_WINHTTP
#   USE_SHA1=CollisionDetection -> GIT_SHA1_COLLISIONDETECT
#   USE_SHA256=Win32         -> GIT_SHA256_WIN32
#   USE_HTTP_PARSER=builtin  -> GIT_HTTPPARSER_BUILTIN (bundled llhttp)
#   REGEX_BACKEND=pcre2      -> GIT_REGEX_PCRE2
#   USE_SSH=OFF              -> TortoiseGit supplies its own ssh transport
#                               (src/libgit2/ssh-wintunnel.c)
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DBUILD_TESTS=OFF
        -DUSE_HTTPS=WinHTTP
        -DUSE_SHA1=CollisionDetection
        -DUSE_SHA256=Win32
        -DUSE_HTTP_PARSER=builtin
        -DREGEX_BACKEND=pcre2
        -DUSE_SSH=OFF
        -DUSE_THREADS=ON
        -DUSE_NSEC=ON
        -DSTATIC_CRT=${STATIC_CRT}
        "-DPKG_CONFIG_EXECUTABLE=${PKGCONFIG}"
        -DCMAKE_DISABLE_FIND_PACKAGE_GSSAPI:BOOL=ON
        ${GIT2_FEATURES}
    OPTIONS_DEBUG
        -DBUILD_CLI=OFF
    MAYBE_UNUSED_VARIABLES
        STATIC_CRT
)

vcpkg_cmake_install()
vcpkg_fixup_pkgconfig()
vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/${PORT}")

if("tools" IN_LIST FEATURES)
    # Since SHA256 is considered an "experimental" feature, it renames the executable. This renames it back.
    if("sha256" IN_LIST FEATURES)
        file(RENAME "${CURRENT_PACKAGES_DIR}/bin/git2-experimental${VCPKG_TARGET_EXECUTABLE_SUFFIX}" "${CURRENT_PACKAGES_DIR}/bin/git2${VCPKG_TARGET_EXECUTABLE_SUFFIX}")
    endif()

    vcpkg_copy_tools(TOOL_NAMES git2 AUTO_CLEAN)
endif()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

# TortoiseGit compiles three of its own sources into libgit2's namespace --
# src/libgit2/{filter-filter,ssh-wintunnel,system-call}.c -- which call libgit2
# internals (git__calloc, git_str_*, git_net_url_*, git_repository_config__weakptr,
# git_filter_buffered_stream_new, ...). Those are reachable when linking the static
# library, but their declarations live in headers upstream does not install.
#
# Install the private header trees so consumers do not have to reach into the
# ext/libgit2 submodule for them (and so they get the *patched* headers, matching
# the library that was actually built). git2_features.h matters most: git2_util.h
# includes it unconditionally unless LIBGIT2_NO_FEATURES_H is defined, and it is
# generated by cmake, so shipping it is what lets consumers skip re-declaring the
# whole feature-flag set by hand.
#
# The two trees stay separate, exactly as upstream's own build puts them on the
# include path: `#include "str.h"` must resolve in util/ and `#include
# "repository.h"` in libgit2/. Consumers add both directories.
set(private_include "${CURRENT_PACKAGES_DIR}/include/libgit2-private")

foreach(subdir IN ITEMS "libgit2" "util")
    file(GLOB_RECURSE private_headers RELATIVE "${SOURCE_PATH}/src/${subdir}" "${SOURCE_PATH}/src/${subdir}/*.h")
    foreach(header IN LISTS private_headers)
        get_filename_component(header_dir "${header}" DIRECTORY)
        file(INSTALL "${SOURCE_PATH}/src/${subdir}/${header}"
             DESTINATION "${private_include}/${subdir}/${header_dir}")
    endforeach()
endforeach()

# git2_util.h does `#include "git2_features.h"`, so it has to sit next to it.
file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/gen_headers/git2_features.h"
     DESTINATION "${private_include}/util")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/COPYING")
