cmake_minimum_required(VERSION 4.0)
project(TortoiseProc LANGUAGES CXX)

find_package(ogdf REQUIRED CONFIG)
find_package(MFC REQUIRED)

add_executable(TortoiseProc)

target_sources(TortoiseProc
    PRIVATE
        AboutDlg.cpp
        AboutDlg.h
        AddDlg.cpp
        AddDlg.h
        AddRemoteDlg.cpp
        AddRemoteDlg.h
        AppUtils.cpp
        AppUtils.h
        AutoTextTestDlg.cpp
        AutoTextTestDlg.h
        BisectStartDlg.cpp
        BisectStartDlg.h
        BranchCombox.h
        BrowseRefsDlg.cpp
        BrowseRefsDlg.h
        BrowseRefsDlgFilter.cpp
        BrowseRefsDlgFilter.h
        BstrSafeVector.h
        BugtraqRegexTestDlg.cpp
        BugtraqRegexTestDlg.h
        ChangedDlg.cpp
        ChangedDlg.h
        CheckCertificateDlg.cpp
        CheckCertificateDlg.h
        CheckForUpdatesDlg.cpp
        CheckForUpdatesDlg.h
        ChooseVersion.h
        CleanTypeDlg.cpp
        CleanTypeDlg.h
        CloneDlg.cpp
        CloneDlg.h
        Colors.cpp
        Colors.h
        ColumnManager.cpp
        ColumnManager.h
        Commands/AboutCommand.cpp
        Commands/AboutCommand.h
        Commands/AddCommand.cpp
        Commands/AddCommand.h
        Commands/AutoTextTestCommand.h
        Commands/BisectCommand.cpp
        Commands/BisectCommand.h
        Commands/BlameCommand.cpp
        Commands/BlameCommand.h
        Commands/BranchCommand.cpp
        Commands/BranchCommand.h
        Commands/CatCommand.cpp
        Commands/CatCommand.h
        Commands/CleanupCommand.cpp
        Commands/CleanupCommand.h
        Commands/CloneCommand.cpp
        Commands/CloneCommand.h
        Commands/Command.cpp
        Commands/Command.h
        Commands/CommitCommand.cpp
        Commands/CommitCommand.h
        Commands/CommitIsOnRefsCommand.cpp
        Commands/CommitIsOnRefsCommand.h
        Commands/ConflictEditorCommand.cpp
        Commands/ConflictEditorCommand.h
        Commands/CreateRepositoryCommand.cpp
        Commands/CreateRepositoryCommand.h
        Commands/DaemonCommand.cpp
        Commands/DaemonCommand.h
        Commands/DiffCommand.cpp
        Commands/DiffCommand.h
        Commands/DropCopyAddCommand.cpp
        Commands/DropCopyAddCommand.h
        Commands/DropCopyCommand.cpp
        Commands/DropCopyCommand.h
        Commands/DropMoveCommand.cpp
        Commands/DropMoveCommand.h
        Commands/ExportCommand.cpp
        Commands/ExportCommand.h
        Commands/FetchCommand.cpp
        Commands/FetchCommand.h
        Commands/FirstStartWizardCommand.cpp
        Commands/FirstStartWizardCommand.h
        Commands/FormatPatchCommand.cpp
        Commands/FormatPatchCommand.h
        Commands/HelpCommand.h
        Commands/IgnoreCommand.cpp
        Commands/IgnoreCommand.h
        Commands/InaccessibleCommand.cpp
        Commands/InaccessibleCommand.h
        Commands/LFSCommands.cpp
        Commands/LFSCommands.h
        Commands/LogCommand.cpp
        Commands/LogCommand.h
        Commands/MergeCommand.cpp
        Commands/MergeCommand.h
        Commands/PasteCopyCommand.cpp
        Commands/PasteMoveCommand.cpp
        Commands/PrevDiffCommand.cpp
        Commands/PrevDiffCommand.h
        Commands/PullCommand.cpp
        Commands/PullCommand.h
        Commands/PushCommand.cpp
        Commands/PushCommand.h
        Commands/RebaseCommand.cpp
        Commands/RebaseCommand.h
        Commands/RefBrowseCommand.h
        Commands/RefLogCommand.cpp
        Commands/RefLogCommand.h
        Commands/RegisterWin11ContextMenu.cpp
        Commands/RegisterWin11ContextMenu.h
        Commands/RemoveCommand.cpp
        Commands/RemoveCommand.h
        Commands/RenameCommand.cpp
        Commands/RenameCommand.h
        Commands/RepositoryBrowserCommand.cpp
        Commands/RepositoryBrowserCommand.h
        Commands/RepoStatusCommand.cpp
        Commands/RepoStatusCommand.h
        Commands/RequestPullCommand.cpp
        Commands/RequestPullCommand.h
        Commands/ResolveCommand.cpp
        Commands/ResolveCommand.h
        Commands/RevertCommand.cpp
        Commands/RevertCommand.h
        Commands/RevisionGraphCommand.cpp
        Commands/RevisionGraphCommand.h
        Commands/RTFMCommand.h
        Commands/SettingsCommand.cpp
        Commands/SettingsCommand.h
        Commands/ShowCompareCommand.cpp
        Commands/ShowCompareCommand.h
        Commands/StashCommand.cpp
        Commands/StashCommand.h
        Commands/SubmoduleCommand.cpp
        Commands/SubmoduleCommand.h
        Commands/SVNDCommitCommand.cpp
        Commands/SVNDCommitCommand.h
        Commands/SVNFetchCommand.cpp
        Commands/SVNFetchCommand.h
        Commands/SVNIgnoreCommand.cpp
        Commands/SVNIgnoreCommand.h
        Commands/SVNRebaseCommand.cpp
        Commands/SVNRebaseCommand.h
        Commands/SwitchCommand.cpp
        Commands/SwitchCommand.h
        Commands/SyncCommand.cpp
        Commands/SyncCommand.h
        Commands/TagCommand.cpp
        Commands/TagCommand.h
        Commands/UpdateCheckCommand.cpp
        Commands/UpdateCheckCommand.h
        Commands/WorktreeCommand.cpp
        Commands/WorktreeCommand.h
        CommitDlg.cpp
        CommitDlg.h
        CommitIsOnRefsDlg.cpp
        CommitIsOnRefsDlg.h
        ConfigureGitExe.h
        CreateBranchTagDlg.cpp
        CreateBranchTagDlg.h
        CreateChangelistDlg.cpp
        CreateChangelistDlg.h
        CreateRepoDlg.cpp
        CreateRepoDlg.h
        CreateWorktreeDlg.cpp
        CreateWorktreeDlg.h
        DeleteConflictDlg.cpp
        DeleteConflictDlg.h
        DeleteRemoteTagDlg.cpp
        DeleteRemoteTagDlg.h
        DiffLinesForStaging.cpp
        DiffLinesForStaging.h
        EnableStagingTypes.h
        ExportDlg.cpp
        ExportDlg.h
        FileDiffDlg.cpp
        FileDiffDlg.h
        FilterHelper.cpp
        FilterHelper.h
        FindBar.cpp
        FindBar.h
        FindDlg.cpp
        FindDlg.h
        FirstStartWizard.cpp
        FirstStartWizard.h
        FirstStartWizardAuthentication.cpp
        FirstStartWizardAuthentication.h
        FirstStartWizardBasePage.cpp
        FirstStartWizardBasePage.h
        FirstStartWizardGit.cpp
        FirstStartWizardGit.h
        FirstStartWizardLanguage.cpp
        FirstStartWizardLanguage.h
        FirstStartWizardStart.cpp
        FirstStartWizardStart.h
        FirstStartWizardUser.cpp
        FirstStartWizardUser.h
        FormatPatchDlg.cpp
        FormatPatchDlg.h
        GitCliOutputParser.cpp
        GitCliOutputParser.h
        GitDiff.cpp
        GitDiff.h
        GitLogCache.cpp
        gitlogcache.h
        GitLogList.h
        GitLogListAction.cpp
        GitLogListBase.cpp
        GitLogListBase.h
        GitProgressDlg.cpp
        GitProgressDlg.h
        GitProgressList.cpp
        GitProgressList.h
        GitRefCompareList.cpp
        GitRefCompareList.h
        GitStatusListCtrlHelpers.cpp
        GitSwitchDlg.cpp
        GitSwitchDlg.h
        GitTagCompareList.cpp
        GitTagCompareList.h
        GravatarPictureBox.cpp
        GravatarPictureBox.h
        HistoryDlg.cpp
        HistoryDlg.h
        IgnoreDlg.cpp
        IgnoreDlg.h
        InputDlg.cpp
        InputDlg.h
        lanes.cpp
        LFSLocksDlg.cpp
        LFSLocksDlg.h
        LogDataVector.cpp
        LogDlg.cpp
        LogDlg.h
        LogDlgFileFilter.cpp
        LogDlgFileFilter.h
        LogDlgFilter.cpp
        LogDlgFilter.h
        LogDlgHelper.h
        LogFile.cpp
        LogFile.h
        LoglistUtils.cpp
        LoglistUtils.h
        LogOrdering.cpp
        LogOrdering.h
        MassiveGitTask.cpp
        MassiveGitTask.h
        MergeAbortDlg.cpp
        MergeAbortDlg.h
        MergeDlg.cpp
        MergeDlg.h
        PatchViewDlg.cpp
        PatchViewDlg.h
        ProgressCommands/AddProgressCommand.cpp
        ProgressCommands/AddProgressCommand.h
        ProgressCommands/CloneProgressCommand.cpp
        ProgressCommands/CloneProgressCommand.h
        ProgressCommands/FetchProgressCommand.cpp
        ProgressCommands/FetchProgressCommand.h
        ProgressCommands/LFSSetLockedProgressCommand.cpp
        ProgressCommands/LFSSetLockedProgressCommand.h
        ProgressCommands/RemoteProgressCommand.cpp
        ProgressCommands/RemoteProgressCommand.h
        ProgressCommands/ResetProgressCommand.cpp
        ProgressCommands/ResetProgressCommand.h
        ProgressCommands/ResolveProgressCommand.cpp
        ProgressCommands/ResolveProgressCommand.h
        ProgressCommands/RevertProgressCommand.cpp
        ProgressCommands/RevertProgressCommand.h
        ProgressDlg.cpp
        ProgressDlg.h
        ProjectProperties.cpp
        ProjectProperties.h
        PromptDlg.cpp
        PromptDlg.h
        PullFetchDlg.cpp
        PullFetchDlg.h
        PushDlg.cpp
        PushDlg.h
        RebaseDlg.cpp
        RebaseDlg.h
        RefLogDlg.cpp
        RefLogDlg.h
        RefLoglist.cpp
        RefLoglist.h
        RenameDlg.cpp
        RenameDlg.h
        RepositoryBrowser.cpp
        RepositoryBrowser.h
        RequestPullDlg.cpp
        RequestPullDlg.h
        ResetDlg.cpp
        ResetDlg.h
        ResolveDlg.cpp
        ResolveDlg.h
        Resource.h
        RevertDlg.cpp
        RevertDlg.h
        RevisionGraph/RevGraphFilterDlg.cpp
        RevisionGraph/RevGraphFilterDlg.h
        RevisionGraph/RevisionGraphDlg.cpp
        RevisionGraph/RevisionGraphDlg.h
        RevisionGraph/RevisionGraphDlgDraw.cpp
        RevisionGraph/RevisionGraphDlgFunc.cpp
        RevisionGraph/RevisionGraphWnd.cpp
        RevisionGraph/RevisionGraphWnd.h
        SelectRemoteRefDlg.cpp
        SelectRemoteRefDlg.h
        Settings/GitSettings.h
        Settings/SetBugTraq.cpp
        Settings/SetBugTraq.h
        Settings/SetBugTraqAdv.cpp
        Settings/SetBugTraqAdv.h
        Settings/SetDialogs.cpp
        Settings/SetDialogs.h
        Settings/SetDialogs2.cpp
        Settings/SetDialogs2.h
        Settings/SetDialogs3.cpp
        Settings/SetDialogs3.h
        Settings/SetExtMenu.h
        Settings/SetHooks.cpp
        Settings/SetHooks.h
        Settings/SetHooksAdv.cpp
        Settings/SetHooksAdv.h
        Settings/SetLookAndFeelPage.cpp
        Settings/SetLookAndFeelPage.h
        Settings/SetMainPage.cpp
        Settings/SetMainPage.h
        Settings/SetOverlayHandlers.cpp
        Settings/SetOverlayHandlers.h
        Settings/SetOverlayIcons.cpp
        Settings/SetOverlayIcons.h
        Settings/SetOverlayPage.cpp
        Settings/SetOverlayPage.h
        Settings/SetProgsAdvDlg.cpp
        Settings/SetProgsAdvDlg.h
        Settings/SetProxyPage.cpp
        Settings/SetProxyPage.h
        Settings/SetSavedDataPage.cpp
        Settings/SetSavedDataPage.h
        Settings/SettingGitConfig.cpp
        Settings/SettingGitConfig.h
        Settings/SettingGitCredential.cpp
        Settings/SettingGitCredential.h
        Settings/SettingGitRemote.cpp
        Settings/SettingGitRemote.h
        Settings/Settings.cpp
        Settings/Settings.h
        Settings/SettingsAdvanced.cpp
        Settings/SettingsAdvanced.h
        Settings/SettingsBugtraqConfig.cpp
        Settings/SettingsBugtraqConfig.h
        Settings/SettingsColors.cpp
        Settings/SettingsColors.h
        Settings/SettingsColors2.cpp
        Settings/SettingsColors2.h
        Settings/SettingsColors3.cpp
        Settings/SettingsColors3.h
        Settings/SettingsProgsAlternativeEditor.cpp
        Settings/SettingsProgsAlternativeEditor.h
        Settings/SettingsProgsDiff.cpp
        Settings/SettingsProgsDiff.h
        Settings/SettingsProgsMerge.cpp
        Settings/SettingsProgsMerge.h
        Settings/SettingsPropPage.cpp
        Settings/SettingsPropPage.h
        Settings/SettingsTBlame.cpp
        Settings/SettingsTBlame.h
        Settings/SettingsTUDiff.cpp
        Settings/SettingsTUDiff.h
        Settings/SetWin11ContextMenu.h
        Settings/ToolAssocDlg.cpp
        Settings/ToolAssocDlg.h
        SimplePrompt.cpp
        SimplePrompt.h
        SinglePropSheetDlg.cpp
        SinglePropSheetDlg.h
        StagingOperations.cpp
        StagingOperations.h
        StashSave.cpp
        StashSave.h
        StatGraphDlg.cpp
        StatGraphDlg.h
        stdafx.cpp
        stdafx.h
        SubmoduleAddDlg.cpp
        SubmoduleAddDlg.h
        SubmoduleDiffDlg.cpp
        SubmoduleDiffDlg.h
        SubmoduleResolveConflictDlg.cpp
        SubmoduleResolveConflictDlg.h
        SubmoduleUpdateDlg.cpp
        SubmoduleUpdateDlg.h
        SVNDCommitDlg.cpp
        SVNDCommitDlg.h
        SVNIgnoreTypeDlg.cpp
        SVNIgnoreTypeDlg.h
        SyncDlg.cpp
        SyncDlg.h
        SyncTabCtrl.cpp
        SyncTabCtrl.h
        TortoiseProc.cpp
        TortoiseProc.h
        UpdateCrypto.cpp
        UpdateCrypto.h
        UpdateDownloader.cpp
        UpdateDownloader.h
        UpdateListCtrl.cpp
        UpdateListCtrl.h
        URLDlg.cpp
        URLDlg.h
        UserPassword.cpp
        UserPassword.h
        VersioncheckParser.cpp
        VersioncheckParser.h
        WorktreeListDlg.cpp
        WorktreeListDlg.h
)

set_target_properties(TortoiseProc PROPERTIES
    CMAKE_MFC_FLAG 2
)

target_compile_features(TortoiseProc
    PRIVATE
        cxx_std_23
        c_std_23
)

target_include_directories(TortoiseProc
    PRIVATE
        "${CMAKE_SOURCE_DIR}/src/Utils"
        "${CMAKE_SOURCE_DIR}/src/Utils/MiscUI"
        "${CMAKE_SOURCE_DIR}/src/Git"
        "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/scintilla2"
        "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/lexilla"
        "$<TARGET_FILE_DIR:TortoiseProc>"
        "${CMAKE_CURRENT_SOURCE_DIR}"
        "${CMAKE_SOURCE_DIR}/src"
        "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include"
)

target_compile_definitions(TortoiseProc
    PRIVATE
        TORTOISEGITPROC
        TGIT_LFS
        _WIN64
        WIN64
        UNICODE
        _UNICODE
        GIT_DEPRECATE_HARD
        ENABLE_INTSAFE_SIGNED_FUNCTIONS
        _WIN32_WINNT=0x0A00
        _WINDOWS
        WINDOWS
        NOMINMAX
        _AFXDLL
        "$<$<CONFIG:Debug>:_DEBUG>"
        "$<$<CONFIG:Debug>:DEBUG>"
        "$<$<CONFIG:Release>:NDEBUG>"
        "$<$<STREQUAL:${CMAKE_CXX_COMPILER_ARCHITECTURE_ID},x64>:_AMD64_>"
        "$<$<STREQUAL:${CMAKE_CXX_COMPILER_ARCHITECTURE_ID},ARM64>:_ARM64_>"
)

target_link_directories(TortoiseProc
    PRIVATE
        "$<$<CONFIG:Debug>:${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib>"
        "$<$<CONFIG:Release>:${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib>"
)

target_link_libraries(TortoiseProc
    PRIVATE
        Winmm
        gdiplus
        shfolder
        comctl32
        ws2_32
        shlwapi
        wininet
        UxTheme
        detours
        OGDF
        COIN
        Scintilla
        Lexilla
        imm32
        msimg32
        ole32
        oleaut32
        winhttp
        rpcrt4
        gdi32
        crypt32
        gitdll
        AsyncFramework
        TGitLibgit2
        ResizableLib
)

target_compile_options(TortoiseProc
    PRIVATE
        /W3
        /external:W0
        /external:anglebrackets
)

