// TortoiseGit - a Windows shell extension for easy version control

// Copyright (C) 2008-2026 - TortoiseGit

// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software Foundation,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//
// gitdll.cpp : Defines the exported functions for the DLL application.
//
#include <string.h>

// Need to solve this collision
#ifdef COLLISSION_WINSOCK
#include <windows.h>
#endif


#ifndef nullptr
#define nullptr NULL;
#endif

#define USE_THE_REPOSITORY_VARIABLE
// git's feature defines arrive via ForcedIncludeFiles=tgit-libgit-defines.h,
// generated by the port from the compile command the library was actually built
// with. The old "../build/libgit-defines.h" asserted them by hand and had
// drifted; see ext\vcpkg-ports\tgit-libgit.
#include <tgit-libgit/tgit-libgit-defines.h>
#include <tgit-libgit/git-compat-util.h>
#include <tgit-libgit/hash.h>
#include <tgit-libgit/commit.h>
#include <tgit-libgit/config.h>
#include <tgit-libgit/diff.h>
#include <tgit-libgit/diffcore.h>
#include <tgit-libgit/dir.h>
#include <tgit-libgit/entry.h>
#include <tgit-libgit/environment.h>
#include <tgit-libgit/mailmap.h>
#include <tgit-libgit/notes.h>
#include <tgit-libgit/object-name.h>
#include <tgit-libgit/packfile.h>
#include <tgit-libgit/path.h>
#include <tgit-libgit/read-cache.h>
#include <tgit-libgit/revision.h>
#include <tgit-libgit/setup.h>
#include <tgit-libgit/tree.h>
#include <tgit-libgit/compat/posix.h>

#define _CRT_INTERNAL_NONSTDC_NAMES 1  // NOLINT(clang-diagnostic-reserved-macro-identifier, bugprone-reserved-identifier)
#include "gitdll.h"

// Instead of including all builtin.h
int cmd_update_index(int argc, const char** argv, const char* prefix, struct repository* repo);


extern char g_last_error[];
static const char* g_prefix;

/* also see GitHash.h */
static_assert(GIT_SHA1_RAWSZ <= LIBGIT_GIT_HASH_SIZE && GIT_SHA256_RAWSZ <= LIBGIT_GIT_HASH_SIZE && GIT_MAX_RAWSZ == LIBGIT_GIT_HASH_SIZE, "Required to be equal in gitdll.h");
static_assert(sizeof(struct object_id) == sizeof(struct GIT_OBJECT_OID), "Required to be equal in gitdll.h");

extern NORETURN void die_dll(const char* err, va_list params);
extern void handle_error(const char* err, va_list params);
extern void handle_warning(const char* warn, va_list params);
extern int die_is_recursing_dll(void);

extern void libgit_initialize(void);
extern void cleanup_chdir_notify(void);
extern void odb_close_tgit(struct object_database* o);
extern void reset_git_env(const wchar_t*);
extern void drop_all_attr_stacks(void);
extern void git_atexit_dispatch(void);
extern void git_atexit_clear(void);
extern void ref_store_release_and_clear(struct repository* repo);
extern void clear_ref_decorations(void);
extern void cmd_log_init_tgit(int argc, const char** argv, const char* prefix, struct rev_info* rev, struct setup_revision_opt* opt);
extern int log_tree_commit(struct rev_info*, struct commit*);
extern int write_entry(struct cache_entry* ce, char* path, struct conv_attrs* ca, const struct checkout* state, int to_tempfile, int* nr_checkouts);
extern void diff_flush_stat(struct diff_filepair* p, struct diff_options* o, struct diffstat_t* diffstat);
static_assert(sizeof(unsigned long long) == sizeof(timestamp_t), "Required for each_reflog_ent_fn definition in gitdll.h");
extern void reset_setup(void);


static void dll_entry(void)
{
	set_die_routine(die_dll);
	set_error_routine(handle_error);
	set_warn_routine(handle_warning);
	set_die_is_recursing_routine(die_is_recursing_dll);
	libgit_initialize();
}

int git_get_sha1(const char *name, GIT_HASH sha1)
{
	struct object_id oid = { 0 };
	const int ret = repo_get_oid(the_repository, name, &oid);
	hashcpy(sha1, oid.hash, the_repository->hash_algo);
	return ret;
}

/*
 * Hash algorithm of the currently opened repository, using git's own
 * GIT_HASH_* indices (0 = unknown, 1 = sha1, 2 = sha256). TortoiseGit latches
 * this once after git_init() and sizes its object ids accordingly, see GitHash.h.
 */
static int tgit_repo_hash_algo(void)
{
	if (!the_repository || !the_repository->hash_algo)
		return GIT_HASH_UNKNOWN;
	return (int)hash_algo_by_ptr(the_repository->hash_algo);
}

int git_get_hash_algo(void)
{
	return tgit_repo_hash_algo();
}

int git_init(const wchar_t* env)
{
	_set_fmode(_O_BINARY);
	_setmode(_fileno(stdin), _O_BINARY);
	_setmode(_fileno(stdout), _O_BINARY);
	_setmode(_fileno(stderr), _O_BINARY);

	cleanup_chdir_notify();
	fscache_flush();
	reset_setup();
	reset_git_env(env);
	assert(getenv("HOME")); // make sure HOME is already set
	drop_all_attr_stacks();
	repo_config_clear(the_repository);
	g_prefix = setup_git_directory(the_repository);
	repo_config(the_repository, git_default_config, NULL);
	ref_store_release_and_clear(the_repository);
	clear_ref_decorations();

	/*
	 * sha1 and sha256 are both handled now (callers size object ids off
	 * git_get_hash_algo(), see GitHash.h); anything else we do not know about.
	 */
	if (tgit_repo_hash_algo() == GIT_HASH_UNKNOWN)
		die("Unsupported repository object format.");

	return 0;
}

static int git_parse_commit_author(struct GIT_COMMIT_AUTHOR* author, const char* pbuff)
{
	const char* end = strchr(pbuff, '<');
	if (!end || end - pbuff - 1 >= INT_MAX)
		return -1;
	author->Name = pbuff;
	author->NameSize = (int)(end - pbuff - 1);

	pbuff = end +1;
	end = strchr(pbuff, '>');
	if (!end || end[1] != ' ' || end - pbuff >= INT_MAX)
		return -1;
	author->Email = pbuff ;
	author->EmailSize = (int)(end - pbuff);

	pbuff = end + 2;

	author->Date = parse_timestamp(pbuff, &end, 10);
	if (end == pbuff || !end || *end != ' ' || end[1] != '+' && end[1] != '-' || !isdigit(end[2]) || !isdigit(end[3]) || !isdigit(end[4]) || !isdigit(end[5]))
		return -1;
	pbuff = end + 1;
	author->TimeZone = strtol(pbuff, NULL, 10);

	return 0;
}

int git_parse_commit(GIT_COMMIT *commit)
{
	const struct commit* p = commit->m_pGitCommit;

	hashcpy(commit->m_hash, p->object.oid.hash, the_repository->hash_algo);

	commit->m_Encode = NULL;
	commit->m_EncodeSize = 0;

	commit->buffer = detach_commit_buffer(commit->m_pGitCommit, NULL);

	const char* pbuf = commit->buffer;
	while(pbuf)
	{
		if (strncmp(pbuf, "author ", strlen("author ")) == 0)
		{
			const int ret = git_parse_commit_author(&commit->m_Author, pbuf + strlen("author "));
			if(ret)
				return -4;
		}
		else if (strncmp(pbuf, "committer ", strlen("committer ")) == 0)
		{
			const int ret = git_parse_commit_author(&commit->m_Committer, pbuf + strlen("committer "));
			if(ret)
				return -5;

			pbuf = strchr(pbuf,'\n');
			if(pbuf == NULL)
				return -6;
		}
		else if (strncmp(pbuf, "encoding ", strlen("encoding ")) == 0)
		{
			pbuf += strlen("encoding ");
			commit->m_Encode=pbuf;
			const char* end = strchr(pbuf,'\n');
			if (!pbuf || end - pbuf >= INT_MAX)
				return -7;
			commit->m_EncodeSize= (int)(end -pbuf);
		}

		// the headers end after the first empty line
		else if (*pbuf == '\n')
		{
			++pbuf;

			commit->m_Subject=pbuf;
			const char* end = strchr(pbuf,'\n');
			if (!end)
			{
				const size_t subjLen = strlen(pbuf);
				if (subjLen >= INT_MAX)
					return -8;
				commit->m_SubjectSize = (int)subjLen;
			}
			else
			{
				if (end - pbuf >= INT_MAX)
					return -9;
				commit->m_SubjectSize = (int)(end - pbuf);
				pbuf = end +1;
				commit->m_Body = pbuf;
				const size_t bodyLen = strlen(pbuf);
				if (bodyLen >= INT_MAX)
					return -10;
				commit->m_BodySize = (int)bodyLen;
				return 0;
			}
		}

		pbuf = strchr(pbuf,'\n');
		if(pbuf)
			++pbuf;
	}
	return 0;
}

int git_get_commit_from_hash(GIT_COMMIT* commit, const GIT_HASH hash)
{
	struct commit *p;
	struct object_id oid = {0};

	if (commit == NULL)
		return -1;

	memset(commit,0,sizeof(GIT_COMMIT));

	hashcpy(oid.hash, hash, the_repository->hash_algo);
	oid.algo = tgit_repo_hash_algo();

	commit->m_pGitCommit = p = lookup_commit(the_repository, &oid);

	if(p == NULL)
		return -1;

	const int ret = repo_parse_commit(the_repository, p);
	if( ret )
		return ret;

	return git_parse_commit(commit);
}

int git_get_commit_first_parent(const GIT_COMMIT* commit, GIT_COMMIT_LIST* list)
{
	const struct commit *p = commit->m_pGitCommit;

	if(list == NULL)
		return -1;

	*list = p->parents;
	return 0;
}

int git_commit_is_root(const GIT_COMMIT* commit)
{
	const struct commit* p = commit->m_pGitCommit;
	return (struct commit_list**)p->parents ? 1 : 0;
}

int git_get_commit_next_parent(GIT_COMMIT_LIST *list, GIT_HASH hash)
{
	if (list == NULL)
		return -1;

	struct commit_list* l = *(struct commit_list**)list;
	if (l == NULL)
		return -1;

	if(hash)
		hashcpy(hash, l->item->object.oid.hash, the_repository->hash_algo);

	*list = l->next;
	return 0;

}


int git_free_commit(GIT_COMMIT *commit)
{
	struct commit *p = commit->m_pGitCommit;

	if( p->parents)
		commit_list_free(p->parents);

	if (p->maybe_tree)
		free_tree_buffer(p->maybe_tree);

	free_commit_buffer(the_repository->parsed_objects, p);
	free((void*)commit->buffer);

	p->object.parsed = 0;
	p->parents = 0;
	p->maybe_tree = NULL;

	memset(commit,0,sizeof(GIT_COMMIT));
	return 0;
}

int git_open_log(GIT_LOG* handle, const int argc, const char** argv)
{
	struct setup_revision_opt opt;

	assert(argc && argv);

	/* clear flags */
	const unsigned int obj_size = get_max_object_index(the_repository);
	for (unsigned int i = 0; i < obj_size; ++i)
	{
		struct object* ob = get_indexed_object(the_repository, i);
		if(ob)
		{
			ob->flags=0;
			if (ob->parsed && ob->type == OBJ_COMMIT)
			{
				struct commit* commit = (struct commit*)ob;
				commit_list_free(commit->parents);
				commit->parents = NULL;
				if (commit->maybe_tree)
					free_tree_buffer(commit->maybe_tree);
				commit->maybe_tree = NULL;
				ob->parsed = 0;
			}
		}
	}

	struct rev_info* p_Rev = malloc(sizeof(struct rev_info));
	if (!p_Rev)
		return -1;

	memset(p_Rev,0,sizeof(struct rev_info));
	*handle = p_Rev; // set this before an exception may be thrown in gitdll so that we don't leak memory

	ref_store_release_and_clear(the_repository);
	clear_ref_decorations();

	repo_init_revisions(the_repository, p_Rev, g_prefix);
	p_Rev->diff = 1;

	memset(&opt, 0, sizeof(opt));
	opt.def = "HEAD";

	cmd_log_init_tgit(argc, argv, g_prefix, p_Rev, &opt);

	p_Rev->pPrivate = (void*)argv; // set last, so if an exception is thrown in gitdll it will not get freed twice
	return 0;

}
int git_get_log_firstcommit(const GIT_LOG handle)
{
	return prepare_revision_walk(handle);
}

int git_get_log_estimate_commit_count(const GIT_LOG handle)
{
	struct rev_info* p_Rev = (struct rev_info*)handle;

	const struct commit_list* list = p_Rev->commits;
	int n = 0;
	while (list)
	{
		const struct commit* commit = list->item;
		const unsigned int flags = commit->object.flags;
		list = list->next;
		if (!(flags & (TREESAME | UNINTERESTING)))
			++n;
	}
	return n;
}

int git_get_log_nextcommit(const GIT_LOG handle, GIT_COMMIT* commit, const int follow)
{
	struct rev_info* p_Rev = (struct rev_info*)handle;
	if(!commit)
		return -1;

	memset(commit, 0, sizeof(GIT_COMMIT));

	commit->m_pGitCommit = get_revision(p_Rev);
	if( commit->m_pGitCommit == NULL)
		return -2;

	if (follow)
	{
		p_Rev->diffopt.no_free = 1;
		if (!log_tree_commit(p_Rev, (struct commit* )commit->m_pGitCommit))
		{
			commit->m_ignore = 1;
			return 0;
		}
	}
	commit->m_ignore = 0;

	const int ret = git_parse_commit(commit);
	if(ret)
		return ret;

	return 0;
}

struct notes_tree **display_notes_trees;
int git_close_log(const GIT_LOG handle, const int releaseRevsisions)
{
	if(handle)
	{
		struct rev_info* p_Rev = handle;
		p_Rev->diffopt.no_free = 0;
		if (releaseRevsisions)
			release_revisions(p_Rev);
		diff_free(&p_Rev->diffopt);
		free(p_Rev->pPrivate);
		free(handle);
	}
	odb_close_tgit(the_repository->objects);

	if (display_notes_trees)
		free_notes(*display_notes_trees);
	display_notes_trees = 0;
	return 0;
}

int git_open_diff(GIT_DIFF* diff, const int argc, const char** argv)
{
	assert(argc && argv);

	struct rev_info* p_Rev = malloc(sizeof(struct rev_info));
	if (!p_Rev)
		return -1;
	memset(p_Rev,0,sizeof(struct rev_info));

	*diff = (GIT_DIFF)p_Rev;

	repo_init_revisions(the_repository, p_Rev, g_prefix);
	repo_config(the_repository, git_diff_basic_config, NULL); /* no "diff" UI options */
	p_Rev->abbrev = 0;
	p_Rev->diff = 1;
	setup_revisions(argc, argv, p_Rev, NULL);

	return 0;
}
int git_close_diff(const GIT_DIFF handle)
{
	git_diff_flush(handle);
	free(handle);
	return 0;
}
int git_diff_flush(const GIT_DIFF diff)
{
	struct diff_queue_struct *q = &diff_queued_diff;
	struct rev_info* p_Rev = diff;

	if(q->nr == 0)
		return 0;

	for (int i = 0; i < q->nr; ++i)
		diff_free_filepair(q->queue[i]);

	if(q->queue)
	{
		free((void*)q->queue);
		q->queue = NULL;
		q->nr = q->alloc = 0;
	}

	if (p_Rev->diffopt.close_file)
		fclose(p_Rev->diffopt.file);

	free_diffstat_info(&p_Rev->diffstat);
	return 0;
}

int git_root_diff(const GIT_DIFF diff, const GIT_HASH hash, GIT_FILE* file, int* count, const int isstat)
{
	struct object_id oid = {};
	struct diff_queue_struct *q = &diff_queued_diff;

	struct rev_info* p_Rev = diff;

	hashcpy(oid.hash, hash, the_repository->hash_algo);
	oid.algo = tgit_repo_hash_algo();

	diff_root_tree_oid(&oid, "", &p_Rev->diffopt);

	if(isstat)
	{
		diffcore_std(&p_Rev->diffopt);

		memset(&p_Rev->diffstat, 0, sizeof(struct diffstat_t));
		for (int i = 0; i < q->nr; ++i) {
			struct diff_filepair *p = q->queue[i];
			//if (check_pair_status(p))
			diff_flush_stat(p, &p_Rev->diffopt, &p_Rev->diffstat);
		}
	}

	if (file)
		*file = q;
	if (count)
		*count = q->nr;

	return 0;
}

int git_do_diff(const GIT_DIFF diff, const GIT_HASH hash1, const GIT_HASH hash2, GIT_FILE* file, int* count, const int isstat)
{
	struct object_id oid1 = {};
	struct object_id oid2 = {};
	struct diff_queue_struct *q = &diff_queued_diff;

	struct rev_info* p_Rev = (struct rev_info*)diff;

	hashcpy(oid1.hash, hash1, the_repository->hash_algo);
	oid1.algo = tgit_repo_hash_algo();
	hashcpy(oid2.hash, hash2, the_repository->hash_algo);
	oid2.algo = tgit_repo_hash_algo();

	struct diff_options* diffopt = &p_Rev->diffopt;
	diff_tree_oid(&oid1, &oid2, "", diffopt);

	if(isstat)
	{
		diffcore_std(&p_Rev->diffopt);
		memset(&p_Rev->diffstat, 0, sizeof(struct diffstat_t));
		for (int i = 0; i < q->nr; ++i) {
			struct diff_filepair *p = q->queue[i];
			//if (check_pair_status(p))
			diff_flush_stat(p, &p_Rev->diffopt, &p_Rev->diffstat);
		}
	}
	odb_close_tgit(the_repository->objects);
	if(file)
		*file = q;
	if(count)
		*count = q->nr;
	return 0;
}

int git_get_diff_file(const GIT_DIFF diff, const GIT_FILE file, const int i, char** newname, char** oldname, int* IsDir, char* status, int* IsBin, int* inc, int* dec)
{
	struct rev_info* const p_Rev = (struct rev_info*)diff;

	const struct diff_queue_struct* q = (struct diff_queue_struct *)file;
	if(file == NULL)
		return -1;
	if(i>=q->nr)
		return -1;

	assert(newname && oldname && status && IsDir);

	*newname = q->queue[i]->two->path;
	*oldname = q->queue[i]->one->path;
	*status = q->queue[i]->status;
	if (*status == 'D')
		*IsDir = (q->queue[i]->one->mode & S_IFDIR) == S_IFDIR;
	else
		*IsDir = (q->queue[i]->two->mode & S_IFDIR) == S_IFDIR;

	if (q->queue[i]->one->mode && q->queue[i]->two->mode && DIFF_PAIR_TYPE_CHANGED(q->queue[i]))
		*IsDir = 0;

	if(p_Rev->diffstat.files)
	{
		int j;
		for (j = 0; j < p_Rev->diffstat.nr; ++j)
		{
			if(strcmp(*newname,p_Rev->diffstat.files[j]->name)==0)
				break;
		}
		if( j== p_Rev->diffstat.nr)
		{
			*IsBin=1;
			*inc=0;
			*dec=0;
			return 0;
		}
		if(IsBin)
			*IsBin = p_Rev->diffstat.files[j]->is_binary;
		if(inc)
			*inc = (int)p_Rev->diffstat.files[j]->added;
		if(dec)
			*dec = (int)p_Rev->diffstat.files[j]->deleted;
	}else
	{
		*IsBin=1;
		*inc=0;
		*dec=0;
	}

	return 0;
}

int git_add_exclude(const char *string, const char *base,
					const int baselen, const EXCLUDE_LIST which, const int lineno)
{
	add_pattern(string, base, baselen, which, lineno);
	return 0;
}

int git_create_exclude_list(EXCLUDE_LIST *which)
{
	*which = malloc(sizeof(struct pattern_list));
	if (!*which)
		return -1;
	memset(*which, 0, sizeof(struct pattern_list));
	return 0;
}

int git_free_exclude_list(const EXCLUDE_LIST which)
{
	struct pattern_list* p = which;

	for (int i = 0; i < p->nr; ++i)
	{
		free(p->patterns[i]);
	}
	free((void*)p->patterns);
	free(p);
	return 0;
}

int git_check_excluded_1(const char *pathname,
							const int pathlen, const char *basename, int *dtype,
							const EXCLUDE_LIST el, const int ignorecase)
{
	ignore_case = ignorecase;
	return path_matches_pattern_list(pathname, pathlen, basename, dtype, el, NULL);
}

int git_get_notes(const GIT_HASH hash, char** p_note)
{
	struct object_id oid = {};
	struct strbuf sb = {};
	size_t size = 0;
	strbuf_init(&sb,0);
	hashcpy(oid.hash, hash, the_repository->hash_algo);
	oid.algo = tgit_repo_hash_algo();
	format_display_notes(&oid, &sb, "utf-8", 1);
	*p_note = strbuf_detach(&sb,&size);

	return 0;
}

int git_update_index(void)
{
	const char* argv[] = { "", "-q", "--refresh" };
	const int argc = sizeof(argv) / sizeof(*argv);

	cleanup_chdir_notify();
	drop_all_attr_stacks();

	const int ret = cmd_update_index(argc, argv, NULL, the_repository);

	discard_index(the_repository->index);
	odb_close_tgit(the_repository->objects);

	return ret;
}

void git_exit_cleanup(void)
{
	git_atexit_dispatch();
	// do not clear the atexit list, as lots of methods register it just once (and have a local static int flag)
}

int git_for_each_reflog_ent(const char *ref, each_reflog_ent_fn fn, void *cb_data)
{
	return refs_for_each_reflog_ent(get_main_ref_store(the_repository) , ref, fn, cb_data);
}

static int update_some(const struct object_id* sha1, const struct strbuf* base, const char* pathname, const unsigned mode, void* context)
{
	struct cache_entry* ce = (struct cache_entry*)context;

	if (S_IFDIR | mode)
		return READ_TREE_RECURSIVE;

	oidcpy(&ce->oid, sha1);
	memcpy(ce->name, base->buf, base->len);
	memcpy(ce->name + base->len, pathname, strlen(pathname));
	ce->ce_flags = create_ce_flags((unsigned int)(strlen(pathname) + base->len));
	ce->ce_mode = create_ce_mode(mode);

	return 0;
}

int git_checkout_file(const char* ref, const char* path, char* outputpath)
{
	struct object_id oid;
	struct checkout state = CHECKOUT_INIT;
	struct pathspec pathspec;
	struct conv_attrs ca;
	const char* matchbuf[1] = {};
	{
		const int ret = repo_get_oid(the_repository, ref, &oid);
		if(ret)
			return ret;
	}

	odb_reprepare(the_repository->objects);
	struct tree* root = parse_tree_indirect(&oid);

	if(!root)
	{
		odb_close_tgit(the_repository->objects);
		return -1;
	}

	struct cache_entry* const ce = (struct cache_entry*)xcalloc(1, cache_entry_size(strlen(path)));

	matchbuf[0] = NULL;
	parse_pathspec(&pathspec, PATHSPEC_ALL_MAGIC, PATHSPEC_PREFER_CWD, path, matchbuf);
	pathspec.items[0].nowildcard_len = pathspec.items[0].len;
	{
		const int ret = read_tree(the_repository, root, &pathspec, update_some, ce);
		clear_pathspec(&pathspec);
		if(ret) {
			odb_close_tgit(the_repository->objects);
			free(ce);
			return ret;
		}
	}

	state.force = 1;
	state.refresh_cache = 0;
	state.istate = the_repository->index;

	reset_parsed_attributes();
	convert_attrs(state.istate, &ca, path);

	{
		const int ret = write_entry(ce, outputpath, &ca, &state, 0, NULL);
		odb_close_tgit(the_repository->objects);
		free(ce);
		return ret;
	}
}
struct config_buf
{
	char *buf;
	const char *key;
	size_t size;
	int seen;
};

static int get_config(const char* key_, const char* value_, const struct config_context* ctx, void* cb)
{
	UNREFERENCED_PARAMETER(ctx);
	struct config_buf *buf = cb;
	if(strcmp(key_, buf->key) != 0)
		return 0;

	if (value_)
		strncpy_s(buf->buf, buf->size, value_, strlen(value_));
	else
	{
		assert(buf->size >= 5);
		buf->buf[0] = 't';
		buf->buf[1] = 'r';
		buf->buf[2] = 'u';
		buf->buf[3] = 'e';
		buf->buf[4] = 0;
	}
	buf->seen = 1;
	return 0;

}

// wchar_t wrapper for git_etc_gitconfig()
const wchar_t* wget_msysgit_etc(wchar_t** env)
{
	static const wchar_t *etc_gitconfig = NULL;
	wchar_t wpointer[MAX_PATH];

	if (etc_gitconfig)
		return etc_gitconfig;

	build_libgit_environment(env);
	char* systemconfig = git_system_config();
	if (xutftowcs_path(wpointer, systemconfig) < 0)
	{
		free(systemconfig);
		return NULL;
	}
	free(systemconfig);

	etc_gitconfig = _wcsdup(wpointer);

	return etc_gitconfig;
}

int git_get_config(const char *key, char *buffer, const int size)
{
	struct config_options opts = { .respect_includes = 1, .ignore_repo = 0};
	struct config_buf buf = { .buf = buffer, .size = size, .seen = 0, .key = key };

	if (have_git_dir())
	{
		opts.git_dir = repo_get_git_dir(the_repository);
		char* local = repo_git_path(the_repository, "config");
		struct git_config_source config_source = {};
		config_source.file = local;
		config_with_options(get_config, &buf, &config_source, the_repository, &opts);
		free(local);
		if (buf.seen)
			return !buf.seen;
	}

	char* global = nullptr;
	char* globalxdg = nullptr;
	git_global_config_paths(&global, &globalxdg);
	if (globalxdg)
	{
		struct git_config_source config_source = {};
		config_source.file = globalxdg;
		config_with_options(get_config, &buf, &config_source, the_repository, &opts);
		free(globalxdg);
		globalxdg = NULL;
		if (buf.seen)
		{
			free(global);
			return !buf.seen;
		}
	}
	if (global)
	{
		struct git_config_source config_source = {};
		config_source.file = global;
		config_with_options(get_config, &buf, &config_source, the_repository, &opts);
		free(global);
		global = NULL;
		if (buf.seen)
			return !buf.seen;
	}

	char* system = git_system_config();
	if (system)
	{
		struct git_config_source config_source = {};
		config_source.file = system;
		config_with_options(get_config, &buf, &config_source, the_repository, &opts);
		free(system);
		if (buf.seen)
			return !buf.seen;
	}

	return !buf.seen;
}

const char* git_default_notes_ref(void)
{
	return default_notes_ref(the_repository);
}

int git_set_config(const char* key, const char* value, const CONFIG_TYPE type)
{
	char* config_exclusive_filename;

	switch(type)
	{
	case CONFIG_LOCAL:
		if (!the_repository || !the_repository->gitdir)
			die("repository not correctly initialized.");
		config_exclusive_filename = repo_git_path(the_repository, "config");
		break;
	case CONFIG_GLOBAL:
	case CONFIG_XDGGLOBAL:
		{
			char* global = NULL;
			char* globalxdg = NULL;
			git_global_config_paths(&global, &globalxdg);
			if (type == CONFIG_GLOBAL)
			{
				config_exclusive_filename = global;
				global = NULL;
			}
			else
			{
				config_exclusive_filename = globalxdg;
				globalxdg = NULL;
			}
			free(global);
			free(globalxdg);
		}
		break;
	default:
		die("repository not correctly initialized.");
	}

	if(!config_exclusive_filename)
		return -1;

	const int ret = repo_config_set_multivar_in_file_gently(the_repository, config_exclusive_filename, key, value, NULL, NULL, 0);
	free(config_exclusive_filename);
	return ret;
}

struct mailmap_info {
	char *name;
	char *email;
};

struct mailmap_entry {
	/* name and email for the simple mail-only case */
	char *name;
	char *email;

	/* name and email for the complex mail and name matching case */
	struct string_list namemap;
};

int git_read_mailmap(GIT_MAILMAP *mailmap)
{
	struct string_list *map;
	int result;

	if (!mailmap)
		return -1;

	*mailmap = NULL;
	if ((map = (struct string_list *)calloc(1, sizeof(struct string_list))) == NULL)
		return -1;

	if ((result = read_mailmap(the_repository, map)) != 0)
	{
		clear_mailmap(map);
		free(map);
		return result;
	}

	if (!map->items)
	{
		clear_mailmap(map);
		free(map);
		 
		return -1;
	}

	*mailmap = map;
	return 0;
}

int git_lookup_mailmap(const GIT_MAILMAP mailmap, const char** email1, const char** name1, const char* email2, void* payload, const char *(*author2_cb)(void*))
{
	if (!mailmap)
		return -1;

	const struct string_list* map = (struct string_list*)mailmap;
	const struct string_list_item* si = string_list_lookup(map, email2);
	if (!si)
		return -1;

	struct mailmap_entry* me = (struct mailmap_entry*)si->util;
	if (me->namemap.nr) {
		/* The item has multiple items */
		const char* author2 = author2_cb(payload);
		struct string_list_item* subitem = string_list_lookup(&me->namemap, author2);
		if (subitem)
			me = (struct mailmap_entry*)subitem->util;
	}

	if (email1)
		*email1 = me->email;
	if (name1)
		*name1 = me->name;
	return 0;
}

void git_free_mailmap(const GIT_MAILMAP mailmap)
{
	if (!mailmap)
		return;

	clear_mailmap((struct string_list *)mailmap);
	free(mailmap);
}

// just for regression tests
int git_mkdir(const char* path)
{
	return mkdir(path, 0);
}

#ifdef _WINDLL

// API Entry Points
// ReSharper disable once CppUseInternalLinkage
BOOL APIENTRY DllMain(const HMODULE hModule, const DWORD ul_reason_for_call, const LPVOID lpReserved) {
	UNREFERENCED_PARAMETER(hModule);
	UNREFERENCED_PARAMETER(lpReserved);
	switch (ul_reason_for_call) {
		case DLL_PROCESS_ATTACH:
			set_die_routine(die_dll);
			set_error_routine(handle_error);
			set_warn_routine(handle_warning);
			set_die_is_recursing_routine(die_is_recursing_dll);
			libgit_initialize();
			break;
		case DLL_THREAD_ATTACH:
		case DLL_THREAD_DETACH:
		case DLL_PROCESS_DETACH:
			break;
		default:
			return false;
	}
	return true;
}

#endif
